import { useAuth, type UserRole } from "../context/AuthContext";
import "./RoleDashboardPage.css";

type DashboardContent = { title: string; subtitle: string; stats: { label: string; value: string; trend: string; positive?: boolean }[]; focusTitle: string; focusValue: string; tableTitle: string; columns: string[]; rows: string[][] };

const dashboards: Record<UserRole, DashboardContent> = {
  SALES_REP: { title: "Your sales workspace", subtitle: "Focus on the opportunities that move your pipeline forward.", stats: [{ label: "Open deals", value: "18", trend: "+3 this week", positive: true }, { label: "Pipeline value", value: "$186K", trend: "+12.4%", positive: true }, { label: "Tasks due", value: "6", trend: "2 due today" }, { label: "Win rate", value: "31%", trend: "+4.2%", positive: true }], focusTitle: "Monthly activity", focusValue: "12 qualified opportunities", tableTitle: "Priority deals", columns: ["Account", "Stage", "Value", "Next step"], rows: [["Northstar Labs", "Proposal", "$42,000", "Follow up Thu"], ["Orbit Systems", "Discovery", "$28,500", "Book demo"], ["Meridian Co.", "Negotiation", "$35,200", "Send contract"]] },
  SALES_MANAGER: { title: "Sales performance", subtitle: "Track team activity, revenue and the pipeline at a glance.", stats: [{ label: "Team revenue", value: "$482K", trend: "+12.4%", positive: true }, { label: "Deals closed", value: "138", trend: "+8.1%", positive: true }, { label: "Active reps", value: "24", trend: "+2 this month", positive: true }, { label: "Pipeline value", value: "$1.2M", trend: "Needs attention" }], focusTitle: "Top region", focusValue: "West Coast · 38% of revenue", tableTitle: "Team pipeline", columns: ["Representative", "Region", "Deals", "Status"], rows: [["Ava Thompson", "West", "22", "On target"], ["Marcus Lee", "East", "18", "On target"], ["Priya Nair", "North", "15", "Review needed"]] },
  TECH_LEAD: { title: "Engineering delivery", subtitle: "Keep your projects, releases and team priorities aligned.", stats: [{ label: "Active projects", value: "8", trend: "2 shipping soon", positive: true }, { label: "Open tasks", value: "37", trend: "9 high priority" }, { label: "Release health", value: "92%", trend: "+5%", positive: true }, { label: "Team capacity", value: "78%", trend: "Healthy" }], focusTitle: "This sprint", focusValue: "14 of 18 planned tasks complete", tableTitle: "Project status", columns: ["Project", "Owner", "Progress", "Status"], rows: [["Client portal", "Maya Chen", "82%", "On track"], ["CRM integration", "Noah Ali", "64%", "In progress"], ["Analytics refresh", "Lena Silva", "38%", "At risk"]] },
  FINANCE_OFFICER: { title: "Financial overview", subtitle: "Review cash flow, invoices and items needing attention.", stats: [{ label: "Receivables", value: "$214K", trend: "+$18K", positive: true }, { label: "Invoices due", value: "16", trend: "4 overdue" }, { label: "Expenses this month", value: "$68K", trend: "Within budget", positive: true }, { label: "Cash position", value: "$1.8M", trend: "+6.2%", positive: true }], focusTitle: "Collections", focusValue: "87% collected on time", tableTitle: "Invoice queue", columns: ["Invoice", "Customer", "Amount", "Status"], rows: [["INV-1048", "Northstar Labs", "$14,200", "Due Friday"], ["INV-1047", "Orbit Systems", "$8,750", "Paid"], ["INV-1045", "Meridian Co.", "$21,000", "Overdue"]] },
  ADMIN: { title: "Administrative overview", subtitle: "Manage your workspace, people and access from one place.", stats: [{ label: "Active users", value: "42", trend: "+4 this month", positive: true }, { label: "Admin tasks", value: "5", trend: "2 need review" }, { label: "System health", value: "99.9%", trend: "All services healthy", positive: true }, { label: "Pending invites", value: "3", trend: "Send reminders" }], focusTitle: "Workspace status", focusValue: "All core services are operating normally", tableTitle: "Recent access activity", columns: ["User", "Role", "Activity", "Status"], rows: [["Ava Thompson", "Sales Rep", "Signed in", "Active"], ["Noah Ali", "Tech Lead", "Updated project", "Active"], ["Priya Nair", "Sales Manager", "Invited teammate", "Active"]] },
};

export default function RoleDashboardPage() {
  const { currentUser } = useAuth();
  const dashboard = dashboards[currentUser?.role ?? "ADMIN"];
  return <div className="role-dashboard"><section className="dashboard-heading"><div><h2>{dashboard.title}</h2><p>{dashboard.subtitle}</p></div><span className="role-chip">{currentUser?.role.replaceAll("_", " ")}</span></section><section className="stats-grid">{dashboard.stats.map((stat) => <article className="stat-card" key={stat.label}><p>{stat.label}</p><strong>{stat.value}</strong><span className={stat.positive ? "positive" : ""}>{stat.trend}</span></article>)}</section><section className="dashboard-grid"><article className="dashboard-card chart-card"><h3>Performance trend</h3><div className="bar-chart">{[43, 62, 51, 77, 58, 90, 71, 96, 65, 84, 76, 100].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div></article><article className="dashboard-card focus-card"><h3>{dashboard.focusTitle}</h3><strong>{dashboard.focusValue}</strong><p>Updated from your workspace activity.</p></article></section><section className="dashboard-card table-card"><h3>{dashboard.tableTitle}</h3><div className="table-scroll"><table><thead><tr>{dashboard.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{dashboard.rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${cell}-${index}`}><span className={index === row.length - 1 ? "table-status" : ""}>{cell}</span></td>)}</tr>)}</tbody></table></div></section></div>;
}
